version: '3.3'
services:
  decadev-docker-oluwatobi:
    container_name: decadev-docker-oluwatobi
    image: decadev-docker-oluwatobi
    build: ./
    ports:
      - "8532:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3340:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oluwatobi
      MYSQL_USER: oluwatobi
      MYSQL_DATABASE: testdb
      MYSQL_PASSWORD: root